import {lessons,items,questions,buildCharacter} from './lessons.js';import {loadProgress,saveProgress} from './progress.js';import {initAudio,playExample} from './audio.js';import './install.js';
const $=id=>document.getElementById(id);let lesson=0,selected=0,question,answered=false,previous='',progress=loadProgress();
function button(text,fn){const b=document.createElement('button');b.type='button';b.textContent=text;b.onclick=fn;return b;}
async function play(id,text){$('play-status').textContent='מכין השמעה…';const r=await playExample(id,text);$('play-status').textContent={recording:'משמיע קובץ שמע.',tts:'משמיע בהקראה של המכשיר — ההגייה עשויה להשתנות.',unavailable:'אין קובץ שמע זמין או קול עברי במכשיר עבור הדוגמה הזאת.'}[r.mode];}
function renderItem(){const d=lessons[lesson].items[selected];$('display').textContent=d.display;$('name').textContent=d.name;$('sound').textContent='צליל / תפקיד: '+d.sound;$('explanation').textContent=d.explanation;$('speak').onclick=()=>play(d.id,d.name+'. '+d.examples[0]);$('examples').replaceChildren(...d.examples.map((w,i)=>{const b=button(w,()=>play(d.id+'-'+i,w));const s=document.createElement('small');s.textContent='🔊 השמעה';b.append(s);return b;}));[...$('marks').children].forEach((b,i)=>b.setAttribute('aria-pressed',String(i===selected)));$('play-status').textContent='';}
function renderLesson(){const l=lessons[lesson];$('lesson-number').textContent='שיעור '+(lesson+1)+' מתוך 4';$('lesson-title').textContent=l.title;$('intro').textContent=l.intro;$('note').textContent=l.note;$('marks').replaceChildren(...l.items.map((d,i)=>{const b=button(d.name,()=>{selected=i;renderItem();});const s=document.createElement('span');s.textContent=d.display;b.prepend(s);return b;}));[...$('tabs').children].forEach((b,i)=>b.setAttribute('aria-pressed',String(i===lesson)));renderItem();newQuestion();}
$('tabs').replaceChildren(...lessons.map((l,i)=>{const b=button('שיעור '+(i+1),()=>{lesson=i;selected=0;renderLesson();});const s=document.createElement('small');s.textContent=l.title;b.append(s);return b;}));
function score(){$('score').textContent=progress.correct+' תשובות נכונות מתוך '+progress.total;}
function newQuestion(){const pool=questions.filter(q=>q.lesson===lesson&&q.answerId!==previous);question=pool[Math.floor(Math.random()*pool.length)];previous=question.answerId;answered=false;$('question').textContent=question.prompt;$('question-instruction').textContent=question.instruction;$('feedback').textContent='';$('next').disabled=true;const shuffled=[...question.choices];for(let i=shuffled.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[shuffled[i],shuffled[j]]=[shuffled[j],shuffled[i]];}$('choices').replaceChildren(...shuffled.map(id=>button(items.find(d=>d.id===id).name,()=>answer(id))));score();}
function answer(id){if(answered)return;answered=true;progress.total++;if(id===question.answerId)progress.correct++;const d=items.find(d=>d.id===question.answerId);$('feedback').textContent=(id===d.id?'✓ נכון! ':'התשובה היא ')+d.name+'. '+d.explanation;saveProgress(progress);score();[...$('choices').children].forEach(b=>b.disabled=true);$('next').disabled=false;}
$('next').onclick=newQuestion;for(const l of 'אבגדהוזחטיכלמנסעפצקרשת')$('letter').add(new Option(l,l));$('letter').value='ב';for(const d of items.filter(d=>!['moving','resting'].includes(d.id)))$('mark').add(new Option(d.name,d.id));function build(){const value=buildCharacter($('letter').value,$('mark').value);$('built').textContent=value??'—';$('build-note').textContent=value?'צירוף חזותי לצורך לימוד.':'הסימן אינו מתאים לאות שנבחרה. בחרו אות או סימן אחר.';}$('letter').onchange=build;$('mark').onchange=build;build();renderLesson();initAudio().then(n=>$('audio-status').textContent=n?'קובצי שמע זמינים':'שמע: הקראה של המכשיר, אם קיים קול עברי');
